import smtplib
from email.message import EmailMessage
from html import escape

from .config import get_settings


def send_otp_email(to: str, code: str, purpose: str | None = None) -> None:
    settings = get_settings()
    is_password_reset = purpose == "passwordReset"
    subject = (
        "Your InTrack password reset OTP"
        if is_password_reset
        else "Your InTrack account activation OTP"
    )

    text_body = "\n\n".join(
        [
            f"Your InTrack - OJT Monitoring System OTP is {code}.",
            "This code expires in 5 minutes.",
            "If you did not request this code, please ignore this message.",
        ]
    )
    html_body = f"""
    <div style="font-family: Arial, sans-serif; color: #0f172a; line-height: 1.5;">
      <h2 style="color: #800000;">InTrack - OJT Monitoring System</h2>
      <p>Your one-time password is:</p>
      <p style="font-size: 28px; font-weight: 700; letter-spacing: 6px; color: #800000;">{escape(code)}</p>
      <p>This code expires in 5 minutes.</p>
      <p style="font-size: 12px; color: #64748b;">If you did not request this code, please ignore this message.</p>
    </div>
    """

    host = settings.effective_smtp_host
    user = settings.effective_smtp_user
    password = settings.effective_smtp_pass

    if not (host and user and password):
        print("OTP email generated by development transport:")
        print(f"To: {to}")
        print(f"Subject: {subject}")
        print(text_body)
        return

    message = EmailMessage()
    message["From"] = settings.effective_smtp_from
    message["To"] = to
    message["Subject"] = subject
    message.set_content(text_body)
    message.add_alternative(html_body, subtype="html")

    if settings.effective_smtp_secure:
        with smtplib.SMTP_SSL(host, settings.effective_smtp_port) as smtp:
            smtp.login(user, password)
            smtp.send_message(message)
    else:
        with smtplib.SMTP(host, settings.effective_smtp_port) as smtp:
            smtp.ehlo()
            if settings.effective_smtp_port == 587:
                smtp.starttls()
                smtp.ehlo()
            smtp.login(user, password)
            smtp.send_message(message)
